name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.14-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --locked

      - name: Run pytest
        run: |
          uv run --locked pytest ./afk_parser/tests -vv
